/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    plans: Plan;
    subscriptions: Subscription;
    'subscription-documents': SubscriptionDocument;
    'transfer-requests': TransferRequest;
    tickets: Ticket;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    plans: PlansSelect<false> | PlansSelect<true>;
    subscriptions: SubscriptionsSelect<false> | SubscriptionsSelect<true>;
    'subscription-documents': SubscriptionDocumentsSelect<false> | SubscriptionDocumentsSelect<true>;
    'transfer-requests': TransferRequestsSelect<false> | TransferRequestsSelect<true>;
    tickets: TicketsSelect<false> | TicketsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale:
    | ('false' | 'none' | 'null')
    | false
    | null
    | ('fr' | 'en' | 'es' | 'zh')
    | ('fr' | 'en' | 'es' | 'zh')[];
  globals: {
    faq: Faq;
    help: Help;
    terms: Term;
    'sales-terms': SalesTerm;
    privacy: Privacy;
    'legal-notice': LegalNotice;
  };
  globalsSelect: {
    faq: FaqSelect<false> | FaqSelect<true>;
    help: HelpSelect<false> | HelpSelect<true>;
    terms: TermsSelect<false> | TermsSelect<true>;
    'sales-terms': SalesTermsSelect<false> | SalesTermsSelect<true>;
    privacy: PrivacySelect<false> | PrivacySelect<true>;
    'legal-notice': LegalNoticeSelect<false> | LegalNoticeSelect<true>;
  };
  locale: 'fr' | 'en' | 'es' | 'zh';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Comptes utilisateurs — gestion des rôles et profils.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  googleId?: string | null;
  authProvider?: ('email' | 'google' | 'apple') | null;
  firstName?: string | null;
  lastName?: string | null;
  roles?: ('developer' | 'admin' | 'comutitres_manager' | 'payer' | 'cardholder' | 'unsubscribed' | 'user')[] | null;
  onboardingCompleted?: boolean | null;
  preferences?: {
    birthdate?: string | null;
    status?: ('student' | 'active' | 'retired' | 'jobseeker' | 'other') | null;
    /**
     * Nombre de jours de trajet par semaine (déclaré)
     */
    usageDaysPerWeek?: number | null;
    /**
     * Bénéficiaire d’un tarif social (RSA, AAH, minima sociaux…)
     */
    socialBeneficiary?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Fichiers et images utilisés dans le catalogue d'offres.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Offres d'abonnement IDFM disponibles à la souscription.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans".
 */
export interface Plan {
  id: string;
  name: string;
  slug: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Illustration de l’offre (affichée en bandeau au-dessus de la carte)
   */
  image?: (string | null) | Media;
  /**
   * Tarif en euros pour la période. Pour Liberté+ : prix au trajet. Pour les offres sur dossier (TST/Améthyste) : 0 + meansTested.
   */
  price: number;
  period: 'per-trip' | 'weekly' | 'monthly' | 'quarterly' | 'annual';
  /**
   * Zones couvertes, ex. "1-5"
   */
  zones?: string | null;
  /**
   * Détermine qui a le droit de souscrire. Champs vides = aucune condition.
   */
  eligibility?: {
    minAge?: number | null;
    maxAge?: number | null;
    /**
     * Réservé aux élèves / étudiants
     */
    studentOnly?: boolean | null;
    /**
     * Soumis à conditions de ressources / dossier (TST, Améthyste)
     */
    meansTested?: boolean | null;
    /**
     * Nécessite une Carte Mobilité Inclusion (Améthyste)
     */
    requiresCMI?: boolean | null;
  };
  /**
   * Sert à recommander l’offre la plus pertinente selon le profil/usage.
   */
  recommendedFor?: {
    /**
     * Âge typique min
     */
    minAge?: number | null;
    /**
     * Âge typique max
     */
    maxAge?: number | null;
    usageDaysPerWeekMin?: number | null;
    usageDaysPerWeekMax?: number | null;
    /**
     * Ex. "Actif temps plein", "Usage occasionnel", "Étudiant"
     */
    profileLabel?: string | null;
  };
  /**
   * Offre proposée aux utilisateurs
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Abonnements IDFM gérés par les comptes utilisateurs.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions".
 */
export interface Subscription {
  id: string;
  plan: string | Plan;
  /**
   * Compte qui gère actuellement cet abonnement (modifié via un transfert)
   */
  managedBy: string | User;
  /**
   * Prénom du titulaire réel (peut être un proche, ≠ titulaire du compte)
   */
  holderFirstName?: string | null;
  holderLastName?: string | null;
  /**
   * N° de carte / support de l’abonnement
   */
  cardNumber?: string | null;
  status?: ('pending' | 'active' | 'expired' | 'cancelled') | null;
  startDate?: string | null;
  endDate?: string | null;
  transferHistory?:
    | {
        fromUser?: (string | null) | User;
        toUser?: (string | null) | User;
        date?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Documents déposés par les usagers pour valider leur souscription.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscription-documents".
 */
export interface SubscriptionDocument {
  id: string;
  owner?: (string | null) | User;
  subscription?: (string | null) | Subscription;
  type?: ('id' | 'photo' | 'school' | 'income' | 'cmi') | null;
  status?: ('pending' | 'validated' | 'refused') | null;
  /**
   * Motif affiché à l'usager en cas de refus
   */
  refusalReason?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Demandes de transfert d'abonnement entre comptes (avec acceptation obligatoire).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transfer-requests".
 */
export interface TransferRequest {
  id: string;
  subscription: string | Subscription;
  /**
   * Email du compte destinataire du transfert
   */
  toEmail: string;
  /**
   * Émetteur (rempli automatiquement)
   */
  fromUser?: (string | null) | User;
  /**
   * Destinataire (résolu depuis l’email)
   */
  toUser?: (string | null) | User;
  status?: ('pending' | 'accepted' | 'declined' | 'cancelled') | null;
  respondedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Demandes de support soumises par les utilisateurs via l'application.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tickets".
 */
export interface Ticket {
  id: string;
  /**
   * Utilisateur ayant soumis le ticket.
   */
  from?: (string | null) | User;
  category: 'subscription' | 'document' | 'lost-card' | 'transfer' | 'billing' | 'other';
  subject: string;
  message: string;
  status?: ('open' | 'in-progress' | 'resolved' | 'closed') | null;
  /**
   * Réponse visible par l'utilisateur dans l'application.
   */
  adminResponse?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'plans';
        value: string | Plan;
      } | null)
    | ({
        relationTo: 'subscriptions';
        value: string | Subscription;
      } | null)
    | ({
        relationTo: 'subscription-documents';
        value: string | SubscriptionDocument;
      } | null)
    | ({
        relationTo: 'transfer-requests';
        value: string | TransferRequest;
      } | null)
    | ({
        relationTo: 'tickets';
        value: string | Ticket;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  googleId?: T;
  authProvider?: T;
  firstName?: T;
  lastName?: T;
  roles?: T;
  onboardingCompleted?: T;
  preferences?:
    | T
    | {
        birthdate?: T;
        status?: T;
        usageDaysPerWeek?: T;
        socialBeneficiary?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans_select".
 */
export interface PlansSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  image?: T;
  price?: T;
  period?: T;
  zones?: T;
  eligibility?:
    | T
    | {
        minAge?: T;
        maxAge?: T;
        studentOnly?: T;
        meansTested?: T;
        requiresCMI?: T;
      };
  recommendedFor?:
    | T
    | {
        minAge?: T;
        maxAge?: T;
        usageDaysPerWeekMin?: T;
        usageDaysPerWeekMax?: T;
        profileLabel?: T;
      };
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions_select".
 */
export interface SubscriptionsSelect<T extends boolean = true> {
  plan?: T;
  managedBy?: T;
  holderFirstName?: T;
  holderLastName?: T;
  cardNumber?: T;
  status?: T;
  startDate?: T;
  endDate?: T;
  transferHistory?:
    | T
    | {
        fromUser?: T;
        toUser?: T;
        date?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscription-documents_select".
 */
export interface SubscriptionDocumentsSelect<T extends boolean = true> {
  owner?: T;
  subscription?: T;
  type?: T;
  status?: T;
  refusalReason?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transfer-requests_select".
 */
export interface TransferRequestsSelect<T extends boolean = true> {
  subscription?: T;
  toEmail?: T;
  fromUser?: T;
  toUser?: T;
  status?: T;
  respondedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tickets_select".
 */
export interface TicketsSelect<T extends boolean = true> {
  from?: T;
  category?: T;
  subject?: T;
  message?: T;
  status?: T;
  adminResponse?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: string;
  title?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "help".
 */
export interface Help {
  id: string;
  title?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms".
 */
export interface Term {
  id: string;
  title?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sales-terms".
 */
export interface SalesTerm {
  id: string;
  title?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy".
 */
export interface Privacy {
  id: string;
  title?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-notice".
 */
export interface LegalNotice {
  id: string;
  title?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "help_select".
 */
export interface HelpSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms_select".
 */
export interface TermsSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sales-terms_select".
 */
export interface SalesTermsSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy_select".
 */
export interface PrivacySelect<T extends boolean = true> {
  title?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-notice_select".
 */
export interface LegalNoticeSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}